/*
Palindrome Partitioning


4

Problem Statement: You are given a string s, partition it in such a way that every
 substring is a palindrome. Return all such palindromic partitions of string s. 
 A palindrome string is a string that reads the same backward as forward.

Examples
Input:  s = “aab”
Output: {["a","a","b"], ["aa","b"]]
Explanation: The first  answer is generated by  making three partitions.
 The second answer is generated by making two partitions.


Input: s = “aabb” 
Output: [[“a”,”a”,”b”,”b”], [“aa”,”bb”], [“a”,”a”,”bb”], [“aa”,”b”,”b”]] 
Explanation : Below are all the partitioning.

*/

#include<bits/stdc++.h>
using namespace std;

vector<vector<string>>partition(string s){
    vector<vector<string>>res;
    vector<string>path;
    func(0,s,path,res);
    return res;
}

void func(int index,string s,vector<string>&path,vector<vector<string>>&res){
    if(index==s.size()){
        res.push_back(path);
        return ;
    }

    for(int i=index;i<s.size();++i){
        if(is_Palindrome(s,index,i)){
            path.push_back(s.substr(index,i-index+1));
            func(i+1,s,path,res);
            path.pop_back();
        }
    }
}

bool is_Palindrome(string s,int start,int end){
    while(start<=end){
        if(s[start++] != s[end--]) return false;
    }
    return true;
}